### ISSUE TITLE
pyodide

### ISSUE THREAD

**Issue by qarlosalberto** [YoWASP/vscode#1]
I see that you are using Pyodide. have you triend with the nodejs flavour? https://www.npmjs.com/package/pyodide

**Comment by whitequark** [comment]
I haven't. This step:

> Download and extract Pyodide packages from [Github releases](https://github.com/pyodide/pyodide/releases) (pyodide-build-*.tar.bz2).

would be problematic for a VS Code extension.

**Comment by qarlosalberto** [comment]
thank you. I was curious about your choice, I'm using it (pyodide nodejs) and I'm having some problems.

**Comment by whitequark** [comment]
I have a compatibility layer for WebWorker API on top of VS Code's Node worker and it lets me use normal Pyodide. (I'm not sure how much of the compatibility is actually required--I think it uses `window.location` at least...)

That might not be very efficient though because it loads a bunch of stuff from the web and relies on Electron to cache it instead of maintaining its own cache. I'm not sure whether that's a problem or not in practice. The main use case for the extension is vscode.dev and the local use case is secondary.

**Comment by qarlosalberto** [comment]
got it! I will try your approach. 

In my case it works fine in debug mode, but not when I pack the extension: https://github.com/pyodide/pyodide/issues/4267

**Comment by whitequark** [comment]
It's probably because of the way you are using the packer (webpack?). My solution, while having  some other downsides, sidesteps this nicely

This isn't an issue with the YoWASP VS Code extension so I'm going to close this one.

**Comment by qarlosalberto** [comment]
I don't use any packer.

Sure, I'm sorry for the offtopic.
